# Default truststore - need to override this to use only the vault truststore config !!
#server:
cloud:
  aws:
    credentials:
      accessKey: MY_ACCESS_KEY
      secretKey: MY_SECRET_KEY
    region.static: us-east-1

aws-app:
  aws:
    service-endpoint: https://example.invalid:9000
